### ISSUE TITLE
Documentation/Infos

### ISSUE THREAD

**Issue by Antidote1911** [RiddleAndCode/aead-io#11]
Coucou,
aead-io look very good. Do you think it can be useful for my file encryptor [cryptyrust](https://github.com/Antidote1911/cryptyrust) ? the encryption routine is [here](https://github.com/Antidote1911/cryptyrust/blob/master/core/src/crypto.rs)

When you have the time, it is possible to make a sample code, in doc or somewhere, to show how to encrypt a file chunk by chunk with aead-io ? Thank for your work.

**Comment by jpopesculian** [comment]
Hey @Antidote1911! Yeah, I can definitely add an example for you if you'd like! I'll see if I can get around to it today

**Comment by jpopesculian** [comment]
@Antidote1911 I added an example https://github.com/RiddleAndCode/aead-io/blob/master/examples/file.rs. Let me know if you have questions!

**Comment by Antidote1911** [comment]
Thank you very much for your help !!! this example is perfect for my experimentations ! Merci beaucoup !!
