### ISSUE TITLE
Consider auto flush on drop?

### ISSUE THREAD

**Issue by kvinwang** [RiddleAndCode/aead-io#9]
I've noticed that if the flush function is not called, the encrypt writer would not finish the encryption.
Sometimes we need to pass the writer to thirdparty codes and it might drop the writer without a direct calling to flush.
Is it better to implement auto flush on drop?

**Comment by jpopesculian** [comment]
Hi @kvinwang! I think I had thoughts about this, and I can't remember why I didn't implement it. But I think it is a good idea, especially considering that `BufWriter` in the standard library implements it https://doc.rust-lang.org/std/io/struct.BufWriter.html#impl-Drop. I'll see if I can get around to implementing it today
